language: go

go:
  - 1.5
  - 1.6.2

install:
  - # Testing
  - go get gopkg.in/stretchr/testify.v1/assert
  - go get gopkg.in/stretchr/testify.v1/mock
  - # Logging
  - go get gopkg.in/Sirupsen/logrus.v1

